name: Deploy GitHub Pages

on:
  pull_request:
    types:
      - closed

jobs:
  deploy:
    name: PMI Prod Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Commit and push changes
        if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged
        run: |
          git config --local user.email "premarketinsights@gmail.com"
          git config --local user.name "Celestiq Insights"
          git add docs
          git commit -m "Deploy to PMI"
          git push origin main
